version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "8443:8443"  # Porta para o webhook, se necessário
    volumes:
      - .:/app  # Monta o diretório atual no contêiner
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge